services:
  web:
    build: .
    volumes:
      - ./TankYouProj:/code
    environment:
      DJANGO_SETTINGS_MODULE: TankYou.settings
      POSTGRES_DB: dragosDB
      POSTGRES_USER: dragos
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dragosDB
      POSTGRES_USER: dragos
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

